name: test_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  email_validator: '^2.1.16'
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/Rectangle.jpg
    - assets/images/Group.png
    - assets/images/Union.png
    - assets/images/Rectangle2.8.jpg
    - assets/images/Rectangle2.9.jpg
    - assets/images/Rectangle2.10.jpg
    - assets/images/Rectangle2.11.jpg

    //ButtonNavBar icons

    - assets/images/bottom_nav_bar_icons/home.png
    - assets/images/bottom_nav_bar_icons/search.png
    - assets/images/bottom_nav_bar_icons/new1.png
    - assets/images/bottom_nav_bar_icons/comment.png
    - assets/images/bottom_nav_bar_icons/person.png

    //User avatars

    - assets/images/users/jane.png
    - assets/images/users/rodjab.png
    - assets/images/users/john.png
    - assets/images/users/sindy.png

    // Photos

    - assets/images/photos/dis1d.jpg
    - assets/images/photos/dis2d.jpg
    - assets/images/photos/dis3d.jpg
    - assets/images/photos/dis4d.jpg
    - assets/images/photos/dis5d.jpg
    - assets/images/photos/dis6d.jpg
    - assets/images/photos/dis7d.jpg
    - assets/images/photos/dis8d.jpg
    - assets/images/photos/dis9d.jpg
    - assets/images/photos/dis10d.jpg

  uses-material-design: true