// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZgmTA6n4nbda0bVEm7TG6WszORTCVw8',
    appId: '1:739623956387:web:cc72a79cac46002f2af416',
    messagingSenderId: '739623956387',
    projectId: 'photo-d121b',
    authDomain: 'photo-d121b.firebaseapp.com',
    storageBucket: 'photo-d121b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-199cDFZADdvLm404LOIUTZUE37eYh68',
    appId: '1:739623956387:android:c3fc7fc3d2f0ac5e2af416',
    messagingSenderId: '739623956387',
    projectId: 'photo-d121b',
    storageBucket: 'photo-d121b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1UR1LLvOyQwBkt9jD24CQi0Svoyg5SWc',
    appId: '1:739623956387:ios:baf4641c727edc9f2af416',
    messagingSenderId: '739623956387',
    projectId: 'photo-d121b',
    storageBucket: 'photo-d121b.appspot.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1UR1LLvOyQwBkt9jD24CQi0Svoyg5SWc',
    appId: '1:739623956387:ios:d619857e21f187d72af416',
    messagingSenderId: '739623956387',
    projectId: 'photo-d121b',
    storageBucket: 'photo-d121b.appspot.com',
    iosBundleId: 'com.example.testApp.RunnerTests',
  );
}
